<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>edge_vibe_detect</name>
  <version>0.1.0</version>
  <description>Excessive vibration detection from IMU</description>
  <maintainer email="dev@example.com">edge_vibe_detect</maintainer>
  <license>Apache-2.0</license>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>edge_sim</depend>
  <depend>edge_perception</depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
